In [28]:
import pandas as pd

df = pd.read_csv("../data/public/raw-data-kaggle.csv", sep=";")


print(df.head())

    athlete gender         timestamp  distance (m)  elapsed time (s)  \
0  18042525      M  15/12/2019 09:08        2965.8               812
1  18042525      M  10/12/2019 19:27       10020.8              3290
2  18042525      M  03/12/2019 19:46       12132.2              4027
3  18042525      M  26/11/2019 19:46       11631.5              4442
4  18042525      M  19/11/2019 19:45       11708.1              4022

   elevation gain (m)  average heart rate (bpm)
0                17.4                     150.3
1                52.2                     160.8
2               249.0                     148.9
3               194.0                     136.2
4               250.7                     146.0

In [29]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42116 entries, 0 to 42115
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   athlete                   42116 non-null  int64
 1   gender                    41761 non-null  object
 2   timestamp                 42116 non-null  object
 3   distance (m)              42116 non-null  float64
 4   elapsed time (s)          42116 non-null  int64
 5   elevation gain (m)        42116 non-null  float64
 6   average heart rate (bpm)  23732 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 2.2+ MB
None

In [30]:
print(df.describe())

            athlete   distance (m)  elapsed time (s)  elevation gain (m)  \
count  4.211600e+04   42116.000000      4.211600e+04        42116.000000
mean   1.503877e+07   11028.352189      4.245974e+03          242.222516
std    8.652464e+06    7480.264547      1.583939e+04          451.664624
min    7.715140e+05       0.000000      0.000000e+00            0.000000
25%    6.583234e+06    7189.600000      2.489750e+03           31.800000
50%    1.388186e+07   10136.750000      3.442000e+03           86.000000
75%    2.065396e+07   13236.300000      4.593250e+03          240.800000
max    4.681758e+07  218950.000000      2.971531e+06        12078.500000

       average heart rate (bpm)
count              23732.000000
mean                 147.652225
std                   17.291873
min                    0.000000
25%                  138.600000
50%                  148.400000
75%                  158.100000
max                  237.000000

In [31]:
df.isna().sum()

athlete                         0
gender                        355
timestamp                       0
distance (m)                    0
elapsed time (s)                0
elevation gain (m)              0
average heart rate (bpm)    18384
dtype: int64

In [32]:
df.dtypes

athlete                       int64
gender                       object
timestamp                    object
distance (m)                float64
elapsed time (s)              int64
elevation gain (m)          float64
average heart rate (bpm)    float64
dtype: object

In [33]:
df["distance_km"] = df["distance (m)"] /1000 
df["elapsed_time_min"] = df["elapsed time (s)"] /60
df.rename(columns={"average heart rate (bpm)": "avg_hr"}, inplace=True)

df["pace_min_per_km"] = df["elapsed_time_min"] / df["distance_km"]

In [34]:
df["has_hr"] = df["avg_hr"].notna().astype(int)
df["gender_encoded"] = df["gender"].map({"M": 1, "F": 0}).fillna(0)

In [35]:
df.head()

,athlete,gender,timestamp,distance (m),elapsed time (s),elevation gain (m),avg_hr,distance_km,elapsed_time_min,pace_min_per_km,has_hr,gender_encoded
0,18042525,M,15/12/2019 09:08,2965.8,812,17.4,150.3,2.9658,13.533333,4.563131,1,1.0
1,18042525,M,10/12/2019 19:27,10020.8,3290,52.2,160.8,10.0208,54.833333,5.471952,1,1.0
2,18042525,M,03/12/2019 19:46,12132.2,4027,249.0,148.9,12.1322,67.116667,5.532110,1,1.0
3,18042525,M,26/11/2019 19:46,11631.5,4442,194.0,136.2,11.6315,74.033333,6.364900,1,1.0
4,18042525,M,19/11/2019 19:45,11708.1,4022,250.7,146.0,11.7081,67.033333,5.725381,1,1.0

In [37]:
new_df = df[["elevation gain (m)", "avg_hr","distance_km",	"elapsed_time_min", "pace_min_per_km", "has_hr", "gender_encoded"]]

In [38]:
new_df.corr()

,elevation gain (m),avg_hr,distance_km,elapsed_time_min,pace_min_per_km,has_hr,gender_encoded
elevation gain (m),1.000000,0.014248,0.667281,0.203775,0.066138,-0.033209,0.040487
avg_hr,0.014248,1.000000,0.088712,-0.011448,-0.106288,NaN,-0.156952
distance_km,0.667281,0.088712,1.000000,0.244388,-0.010091,0.005919,0.061738
elapsed_time_min,0.203775,-0.011448,0.244388,1.000000,0.395454,-0.008790,0.003740
pace_min_per_km,0.066138,-0.106288,-0.010091,0.395454,1.000000,-0.006722,-0.019786
has_hr,-0.033209,NaN,0.005919,-0.008790,-0.006722,1.000000,0.062305
gender_encoded,0.040487,-0.156952,0.061738,0.003740,-0.019786,0.062305,1.000000